import 'ui/src/styles/globals.css';

import type { Metadata } from 'next';
import { headers } from 'next/headers';

import { TrpcClientProvider } from 'api';
import { Wrapper } from 'ui';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TrpcClientProvider headers={headers()}>
          <Wrapper backgroundColor="next">{children}</Wrapper>
        </TrpcClientProvider>
      </body>
    </html>
  );
}
